language: java

jdk: oraclejdk7

script: ./gradlew test jacocoTestReport

after_success: "bash <(curl -s https://codecov.io/bash)"

deploy:
    - provider: bintray
      skip_cleanup: true
      file: "$TRAVIS_BUILD_DIR/.bintray.json"
      user: "konikvranik"
      key: "$BINTRAY_TOKEN"
      on:
          tags: true
    - provider: releases
      overwrite: true
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file: $TRAVIS_BUILD_DIR/build/libs/jtoggl-jackson-*.jar
      on:
         tags: true
