language: java

jdk: oraclejdk7

env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

script: ./gradlew build jacocoTestReport --stacktrace --info

after_success: "bash <(curl -s https://codecov.io/bash)"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - android/build/reports/androidTests/connected/index.html

  skip_cleanup: true
  on:
    tags: true

