language: java

jdk: oraclejdk7

#script: ./gradlew build jacocoTestReport

after_success: "bash <(curl -s https://codecov.io/bash)"

before_deploy:
  - pwd
  - ./gradlew publishMavenPublicationToMavenLocal
  - cd $HOME/.m2/repository && zip -r $HOME/m2repo.zip ch/simas/jtoggl
  - find $TRAVIS_BUILD_DIR/build -type f

deploy:
  #- provider: releases
  #  skip_cleanup: true
  #  api_key: $GITHUB_TOKEN
  #  file:
  #    - $HOME/m2repo.zip
  #    - $TRAVIS_BUILD_DIR/build/libs/jtoggl-jackson-2.0.1-SNAPSHOT.jar
  #  on:
  #    tags: true
  - provider: bintray
    skip_cleanup: true
    file: "$TRAVIS_BUILD_DIR/.bintray.json"
    user: "konikvranik"
    key: "57cbdbcc0ee46556d56eebd61c1c068b362f3925"
    on:
      tags: true
