language: java
jdk: oraclejdk8
env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

script: ./gradlew -p jtoggl-api build jacocoTestReport

after_success: "bash <(curl -s https://codecov.io/bash)"

test:
    post:
        - if [ -e ./gradlew ]; then ./gradlew -p jtoggl-api jacocoTestReport;else gradle -p jtoggl-api jacocoTestReport;fi
        - sudo pip install --user codecov && codecov:
  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - android/build/reports/androidTests/connected/index.html

  skip_cleanup: true
  on:
    tags: true

